### ISSUE TITLE
You cannot attach to a stopped container, start it first. 

### ISSUE THREAD

**Issue by markwoodhall** [ignlg/dokku-newrelic-sysmond#1]
Hi, thanks for putting this together. 

I was having a go at using it yesterday evening and I've not managed to get it working so far. 

```
id=$(docker run -d $IMAGE /bin/bash -c "chmod +x /app/.install-sysmond")
docker attach $id
```

For some reason the above docker attach fails with the error `You cannot attach to a stopped container, start it first` . I've tried looking through docker logs to figure out what caused the container to stop but I've not been able to find anything useful.

**Comment by ignlg** [comment]
Just in case, I have these versions:

```
Dokku version 0.2.3-8-g3b529b3
Docker version 1.4.0-4595d4f
```

If you find what's broken, please, reply here so I can fix it. Btw, a PR to fix the issue would be really appreciated :)
